### ISSUE TITLE
⚡ Standardization of rep

### ISSUE THREAD

**Issue by luxonauta** [dracula/lcd-smartie#1]
Hi @limbo666, We need to adjust a few things first to move forward, OK? ✨

First, we need to update the screenshot!

Can you take a single capture at the closest possible resolution to 1728x1117?

We also need a separate `.md` with installation instructions to show the theme on the site.

I ask for these changes to standardize with the other repositories [see an example](https://github.com/dracula/notepad-plus-plus); this is also important because it helps other potential users who would like to contribute, too! 😁

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by limbo666** [comment]
Hi @luxonauta 
Unfortunately our skinned form of the program (Main interface) doesn't go beyond 865x180 pixels and this may not fit the guidelines of Dracula. Have a look:
![LCD Smartie Interface](https://github.com/dracula/lcd-smartie/assets/331155/02dd6182-a783-4329-9f7b-901d42a8ab99)
I could upscale this a bit, but this could not meet the resolution you are requesting since is going to be pixelated if I push it too much. 

I also created a combined image with our setup page with the skinned main interface which is larger in size but this is not  themed entirely since our setup page doesn't support skins. 
![LCD Smartie Interface 2](https://github.com/dracula/lcd-smartie/assets/331155/8a68467e-1269-4c51-b417-fbb320b3fb76)

Let me know which of the above can be accepted. 

As for the installation `.md`  I have created one [here](https://github.com/dracula/lcd-smartie/blob/main/installation.md). Please check it out.

Waiting for your kind advice 🙂

**Comment by luxonauta** [comment]
The first one is already great! Thanks for the update; I'll also update the [repo](https://github.com/dracula/draculatheme.com) to list it soon!
